# Generated by Django 6.1.1 on 2026-09-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('timeframe', models.CharField(max_length=5)),
                ('strategy', models.CharField(max_length=30)),
                ('params', models.JSONField(default=dict)),
                ('days', models.PositiveIntegerField()),
                ('fee', models.FloatField(default=0.001)),
                ('source', models.CharField(default='ccxt', max_length=10)),
                ('metrics', models.JSONField(default=dict)),
                ('curves', models.JSONField(default=dict)),
                ('validation', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
