# Generated by Django 6.1.1 on 2026-10-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtester', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestrun',
            name='chain',
            field=models.CharField(choices=[('btc', 'Bitcoin'), ('sol', 'Solana'), ('eth', 'Ethereum')], default='btc', max_length=3),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='execution',
            field=models.CharField(default='close', max_length=5),
        ),
    ]
