# Generated by Django 6.1.1 on 2026-10-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtester', '0002_backtestrun_chain_backtestrun_execution'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestrun',
            name='batch',
            field=models.CharField(blank=True, db_index=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='data_note',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='exchange',
            field=models.CharField(default='binance', max_length=20),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='job',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='status',
            field=models.CharField(default='done', max_length=10),
        ),
    ]
