# Generated by Django 6.1.1 on 2026-10-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtester', '0003_backtestrun_batch_backtestrun_data_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestrun',
            name='slippage',
            field=models.FloatField(default=0.0),
        ),
    ]
