# Generated by Django 6.1.1 on 2026-10-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtester', '0004_backtestrun_slippage'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestrun',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
