# Generated by Django 6.1.1 on 2026-10-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtester', '0005_backtestrun_end_date_backtestrun_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestrun',
            name='indicator_lib',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
