# Generated by Django 6.1.1 on 2026-10-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtester', '0006_backtestrun_indicator_lib'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(max_length=20, unique=True)),
                ('until', models.DateTimeField()),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=20)),
                ('timeframe', models.CharField(max_length=5)),
                ('ts', models.BigIntegerField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.FloatField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('exchange', 'symbol', 'timeframe', 'ts'), name='uniq_candle')],
            },
        ),
        migrations.CreateModel(
            name='CandleCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=20)),
                ('timeframe', models.CharField(max_length=5)),
                ('covered_from', models.BigIntegerField()),
                ('covered_to', models.BigIntegerField()),
                ('floor_ts', models.BigIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('exchange', 'symbol', 'timeframe'), name='uniq_candle_coverage')],
            },
        ),
    ]
