# Generated by Django 6.1.1 on 2026-10-06 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backtester", "0008_backtestrun_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="backtestrun",
            name="ai_comment",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="backtestrun",
            name="ai_created",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="backtestrun",
            name="ai_source",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.CreateModel(
            name="AiCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("model", models.CharField(blank=True, default="", max_length=60)),
                ("ok", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_calls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
