# Generated by Django 6.1.1 on 2026-10-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backtester", "0009_ai_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="backtestrun",
            name="signal_alert",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="backtestrun",
            name="signal_state",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
