# Generated by Django 6.1.1 on 2026-10-08 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backtester", "0010_signal_alert"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="backtestrun",
            name="favorite",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="backtestrun",
            name="share_token",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=40
            ),
        ),
        migrations.AddField(
            model_name="backtestrun",
            name="tags",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.CreateModel(
            name="RunTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("job", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="run_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "name"), name="uniq_template_name_per_owner"
                    )
                ],
            },
        ),
    ]
