"""Englische Übersetzungen (automatisch aus dem Prüfwerkzeug erzeugt, von Hand übersetzt)."""
CATALOG = {'Preise gültig': 'Prices valid',
 'Extreme Kurssprünge': 'Extreme price jumps',
 'Kosten berücksichtigt': 'Costs included',
 '{} % je Seite (Gebühr + Slippage) in jeder Position': '{} % per side (fee + slippage) in every position',
 'Realistische Größenordnung': 'Realistic magnitude',
 'doppelte oder unsortierte Kerzen gefunden': 'duplicate or unsorted candles found',
 'eindeutig und aufsteigend': 'unique and ascending',
 'Lücken in den Kursdaten': 'Gaps in the price data',
 '{} Kerzen mit leeren/nicht positiven Preisen': '{} candles with empty/non-positive prices',
 '{} Kerzen mit mehr als 40 % Veränderung (Datenfehler oder Ausnahmeereignis?)': '{} candles with more than 40 % change (data error or '
                                                                                 'exceptional event?)',
 'keine Sprünge über 40 % je Kerze': 'no jumps above 40 % per candle',
 'aus Kursen {} % vs. Kennzahl {} %': 'from prices {} % vs. metric {} %',
 'Kein Blick in die Zukunft': 'No look-ahead',
 'Abhängigkeit vom besten Trade': 'Dependence on the best trade',
 '~(zu wenig für belastbare Aussagen)': '(too little for reliable statements)',
 '{} fehlende Kerzen ({} %)': '{} missing candles ({} %)',
 'keine fehlenden Kerzen': 'no missing candles',
 '{} Kerzen mit widersprüchlichen High/Low/Close': '{} candles with contradictory high/low/close',
 'keine leeren oder widersprüchlichen Werte': 'no empty or contradictory values',
 '{} % der Kerzen ohne Volumen': '{} % of candles without volume',
 'Rendite aus Trades nachgerechnet': 'Return recomputed from trades',
 'Abweichung (Median) {} Prozentpunkte über {} Signal-Trades': 'Deviation (median) {} percentage points over {} signal trades',
 'Trades überlappen oder enden vor dem Einstieg': 'Trades overlap or end before entry',
 'Trades zeitlich geordnet, keine Überschneidung (Long-only)': 'Trades in chronological order, no overlap (long-only)',
 'Signale ändern sich nicht, wenn spätere Kerzen fehlen': 'Signals do not change when later candles are missing',
 'Signale hängen von späteren Kerzen ab: Look-ahead-Fehler': 'Signals depend on later candles: look-ahead error',
 '~(unter 30: statistisch nicht belastbar)': '(under 30: statistically not reliable)',
 '~(unter 180: nur eine Marktphase)': '(under 180: only one market phase)',
 'Ohne den besten Trade: {} % statt {} %': 'Without the best trade: {} % instead of {} %',
 '~– außergewöhnlich gut, zuerst auf Fehler prüfen': '– exceptionally good, check for errors first',
 'Testphase deutlich schlechter als Training: Verdacht auf Überanpassung': 'Test phase clearly worse than training: suspected overfitting',
 'Testphase hält gegenüber dem Training': 'Test phase holds up compared with training',
 'Parameter am Rand des Suchbereichs': 'Parameters at the edge of the search range',
 '~(unter 5: keine Aussage möglich)': '(under 5: no statement possible)',
 '~– der Gewinn hängt an einem einzigen Trade': '– the profit depends on a single trade',
 '~(sehr selten investiert, wenig Datenbasis)': '(rarely invested, little data)',
 '{} liegt am Rand des Rasters: der beste Wert könnte außerhalb liegen': '{} is at the edge of the grid: the best value may lie outside',
 'optimale Parameter liegen im Inneren des Suchbereichs': 'optimal parameters lie in the interior of the search range',
 'Am besten läuft die Strategie in {}-Phasen ({} % bei {} % der Zeit), am schlechtesten in {}-Phasen ({} %). Sie schlägt den Markt in {} von {} Phasen.': 'The '
                                                                                                                                                          'strategy '
                                                                                                                                                          'performs '
                                                                                                                                                          'best '
                                                                                                                                                          'in '
                                                                                                                                                          '{l} '
                                                                                                                                                          'phases '
                                                                                                                                                          '({} '
                                                                                                                                                          '% '
                                                                                                                                                          'during '
                                                                                                                                                          '{} '
                                                                                                                                                          '% '
                                                                                                                                                          'of '
                                                                                                                                                          'the '
                                                                                                                                                          'time), '
                                                                                                                                                          'worst '
                                                                                                                                                          'in '
                                                                                                                                                          '{l} '
                                                                                                                                                          'phases '
                                                                                                                                                          '({} '
                                                                                                                                                          '%). '
                                                                                                                                                          'It '
                                                                                                                                                          'beats '
                                                                                                                                                          'the '
                                                                                                                                                          'market '
                                                                                                                                                          'in '
                                                                                                                                                          '{} '
                                                                                                                                                          'of '
                                                                                                                                                          '{} '
                                                                                                                                                          'phases.',
 'Die Daten bestehen fast nur aus einer Marktphase, Aussagen über andere Phasen sind nicht möglich.': 'The data consists almost entirely '
                                                                                                      'of one market phase; statements '
                                                                                                      'about other phases are not '
                                                                                                      'possible.',
 'Das Ergebnis hängt also stark von der Marktphase ab.': 'The result therefore depends strongly on the market phase.',
 'zu wenige Daten für eine Marktphasen-Analyse': 'too little data for a market phase analysis',
 'zu wenige klassifizierte Kerzen (Zeitraum verlängern)': 'too few classified candles (extend the period)',
 'Der Gewinn verschwindet erst bei ca. {}-fachen Kosten (≈ {} % je Seite).': 'The profit only disappears at roughly {} times the costs (≈ '
                                                                             '{} % per side).',
 'Kostenrobust: Auch bei {}-fachen Kosten bleibt die Rendite positiv ({} %).': 'Cost-robust: even at {} times the costs the return stays '
                                                                               'positive ({} %).',
 'Schon ohne jegliche Kosten ist die Strategie nicht profitabel – die Kosten sind nicht das Problem.': 'The strategy is not profitable '
                                                                                                       'even without any costs – costs are '
                                                                                                       'not the problem.',
 'Mit den angenommenen Kosten ist das Ergebnis negativ. Der Gewinn verschwindet ab ca. {} % je Seite ({}× deiner Annahme).': 'With the '
                                                                                                                             'assumed '
                                                                                                                             'costs the '
                                                                                                                             'result is '
                                                                                                                             'negative. '
                                                                                                                             'The profit '
                                                                                                                             'disappears '
                                                                                                                             'from about '
                                                                                                                             '{} % per '
                                                                                                                             'side ({}× '
                                                                                                                             'your '
                                                                                                                             'assumption).',
 'Fragil: Schon bei {}-fachen Kosten (≈ {} % je Seite) ist die Rendite null. Reale Kosten und Slippage können das Ergebnis aufzehren.': 'Fragile: '
                                                                                                                                        'already '
                                                                                                                                        'at '
                                                                                                                                        '{} '
                                                                                                                                        'times '
                                                                                                                                        'the '
                                                                                                                                        'costs '
                                                                                                                                        '(≈ '
                                                                                                                                        '{} '
                                                                                                                                        '% '
                                                                                                                                        'per '
                                                                                                                                        'side) '
                                                                                                                                        'the '
                                                                                                                                        'return '
                                                                                                                                        'is '
                                                                                                                                        'zero. '
                                                                                                                                        'Real '
                                                                                                                                        'costs '
                                                                                                                                        'and '
                                                                                                                                        'slippage '
                                                                                                                                        'can '
                                                                                                                                        'eat '
                                                                                                                                        'up '
                                                                                                                                        'the '
                                                                                                                                        'result.',
 'Gemischt: {} % der Nachbar-Parameter sind im Plus, der Median der Nachbarn liegt bei {} % (gewählt: {} %). Das Ergebnis reagiert spürbar auf kleine Änderungen.': 'Mixed: '
                                                                                                                                                                    '{} '
                                                                                                                                                                    '% '
                                                                                                                                                                    'of '
                                                                                                                                                                    'the '
                                                                                                                                                                    'neighboring '
                                                                                                                                                                    'parameters '
                                                                                                                                                                    'are '
                                                                                                                                                                    'positive, '
                                                                                                                                                                    'the '
                                                                                                                                                                    'median '
                                                                                                                                                                    'of '
                                                                                                                                                                    'the '
                                                                                                                                                                    'neighbors '
                                                                                                                                                                    'is '
                                                                                                                                                                    '{} '
                                                                                                                                                                    '% '
                                                                                                                                                                    '(chosen: '
                                                                                                                                                                    '{} '
                                                                                                                                                                    '%). '
                                                                                                                                                                    'The '
                                                                                                                                                                    'result '
                                                                                                                                                                    'reacts '
                                                                                                                                                                    'noticeably '
                                                                                                                                                                    'to '
                                                                                                                                                                    'small '
                                                                                                                                                                    'changes.',
 'bei Walk-Forward wechseln die Parameter je Fold; die Stabilität zeigt dort die Parameter-Tabelle der Folds': 'with walk-forward the '
                                                                                                               'parameters change per '
                                                                                                               'fold; the stability is '
                                                                                                               'shown there by the '
                                                                                                               'parameter table of the '
                                                                                                               'folds',
 'für diese Strategie nicht vorgesehen': 'not provided for this strategy',
 'gewählter Parameterpunkt liegt nicht im Raster': 'chosen parameter point is not in the grid',
 'keine gültigen Nachbarwerte im Raster': 'no valid neighboring values in the grid',
 'Schon der gewählte Punkt ist nicht profitabel ({} %); {} % der Nachbarn sind im Plus.': 'Even the chosen point is not profitable ({} %); '
                                                                                          '{} % of the neighbors are positive.',
 'Stabil: {} % der Nachbar-Parameter sind im Plus, der Median der Nachbarn liegt bei {} % (gewählt: {} %). Das Ergebnis hängt nicht an einem Einzelwert.': 'Stable: '
                                                                                                                                                           '{} '
                                                                                                                                                           '% '
                                                                                                                                                           'of '
                                                                                                                                                           'the '
                                                                                                                                                           'neighboring '
                                                                                                                                                           'parameters '
                                                                                                                                                           'are '
                                                                                                                                                           'positive, '
                                                                                                                                                           'the '
                                                                                                                                                           'median '
                                                                                                                                                           'of '
                                                                                                                                                           'the '
                                                                                                                                                           'neighbors '
                                                                                                                                                           'is '
                                                                                                                                                           '{} '
                                                                                                                                                           '% '
                                                                                                                                                           '(chosen: '
                                                                                                                                                           '{} '
                                                                                                                                                           '%). '
                                                                                                                                                           'The '
                                                                                                                                                           'result '
                                                                                                                                                           'does '
                                                                                                                                                           'not '
                                                                                                                                                           'hinge '
                                                                                                                                                           'on '
                                                                                                                                                           'a '
                                                                                                                                                           'single '
                                                                                                                                                           'value.',
 'Spitze statt Plateau: Nur {} % der Nachbar-Parameter sind im Plus, der Median der Nachbarn liegt bei {} % (gewählt: {} %). Das spricht für Überanpassung an genau diesen Wert.': 'Spike '
                                                                                                                                                                                   'instead '
                                                                                                                                                                                   'of '
                                                                                                                                                                                   'plateau: '
                                                                                                                                                                                   'only '
                                                                                                                                                                                   '{} '
                                                                                                                                                                                   '% '
                                                                                                                                                                                   'of '
                                                                                                                                                                                   'the '
                                                                                                                                                                                   'neighboring '
                                                                                                                                                                                   'parameters '
                                                                                                                                                                                   'are '
                                                                                                                                                                                   'positive, '
                                                                                                                                                                                   'the '
                                                                                                                                                                                   'median '
                                                                                                                                                                                   'of '
                                                                                                                                                                                   'the '
                                                                                                                                                                                   'neighbors '
                                                                                                                                                                                   'is '
                                                                                                                                                                                   '{} '
                                                                                                                                                                                   '% '
                                                                                                                                                                                   '(chosen: '
                                                                                                                                                                                   '{} '
                                                                                                                                                                                   '%). '
                                                                                                                                                                                   'This '
                                                                                                                                                                                   'points '
                                                                                                                                                                                   'to '
                                                                                                                                                                                   'overfitting '
                                                                                                                                                                                   'to '
                                                                                                                                                                                   'exactly '
                                                                                                                                                                                   'this '
                                                                                                                                                                                   'value.',
 'Zu wenig Daten fuer Train/Test-Split (Zeitraum oder Zeitfenster vergroessern).': 'Too little data for the train/test split (enlarge the '
                                                                                   'period or timeframe).',
 'Zu wenig Daten fuer die Walk-Forward-Analyse (weniger Folds, kleineres Train-Fenster oder laengeren Zeitraum waehlen).': 'Too little '
                                                                                                                           'data for the '
                                                                                                                           'walk-forward '
                                                                                                                           'analysis '
                                                                                                                           '(choose fewer '
                                                                                                                           'folds, a '
                                                                                                                           'smaller train '
                                                                                                                           'window or a '
                                                                                                                           'longer '
                                                                                                                           'period).',
 'flat (nicht investiert)': 'flat (not invested)',
 'bei synthetischen Daten gibt es kein aktuelles Signal': 'no current signal for synthetic data',
 'zu wenige aktuelle Kursdaten': 'too little current price data',
 'nicht berechenbar: {}': 'not computable: {}',
 'Prüfung nicht möglich': 'check not possible',
 'Größe {} % des Kapitals': 'Size {} % of capital',
 'läuft': 'running',
 'Volatilitätsziel {} % p. a.': 'Volatility target {} % p.a.',
 'long (investiert)': 'long (invested)',
 'wartet': 'waiting',
 'fertig': 'done',
 'Fehler': 'Error',
 'Phase = Kursentwicklung der letzten {} Tage: über +{} % Aufwärts, unter −{} % Abwärts, dazwischen Seitwärts. Im Kurs-Chart sind die Phasen grün (aufwärts) bzw. rot (abwärts) hinterlegt.': 'Phase '
                                                                                                                                                                                              '= '
                                                                                                                                                                                              'price '
                                                                                                                                                                                              'development '
                                                                                                                                                                                              'of '
                                                                                                                                                                                              'the '
                                                                                                                                                                                              'last '
                                                                                                                                                                                              '{} '
                                                                                                                                                                                              'days: '
                                                                                                                                                                                              'above '
                                                                                                                                                                                              '+{} '
                                                                                                                                                                                              '% '
                                                                                                                                                                                              'up, '
                                                                                                                                                                                              'below '
                                                                                                                                                                                              '−{} '
                                                                                                                                                                                              '% '
                                                                                                                                                                                              'down, '
                                                                                                                                                                                              'in '
                                                                                                                                                                                              'between '
                                                                                                                                                                                              'sideways. '
                                                                                                                                                                                              'In '
                                                                                                                                                                                              'the '
                                                                                                                                                                                              'price '
                                                                                                                                                                                              'chart '
                                                                                                                                                                                              'the '
                                                                                                                                                                                              'phases '
                                                                                                                                                                                              'are '
                                                                                                                                                                                              'shaded '
                                                                                                                                                                                              'green '
                                                                                                                                                                                              '(up) '
                                                                                                                                                                                              'or '
                                                                                                                                                                                              'red '
                                                                                                                                                                                              '(down).',
 'Zum Vergleich: Buy & Hold {} %. Gleiche Parameter, nur die Kosten (Gebühr + Slippage) werden vervielfacht. Beim Train/Test-Split gilt die Testphase, bei Walk-Forward gelten die je Fold gewählten Parameter.': 'For '
                                                                                                                                                                                                                  'comparison: '
                                                                                                                                                                                                                  'buy '
                                                                                                                                                                                                                  '& '
                                                                                                                                                                                                                  'hold '
                                                                                                                                                                                                                  '{} '
                                                                                                                                                                                                                  '%. '
                                                                                                                                                                                                                  'Same '
                                                                                                                                                                                                                  'parameters, '
                                                                                                                                                                                                                  'only '
                                                                                                                                                                                                                  'the '
                                                                                                                                                                                                                  'costs '
                                                                                                                                                                                                                  '(fee '
                                                                                                                                                                                                                  '+ '
                                                                                                                                                                                                                  'slippage) '
                                                                                                                                                                                                                  'are '
                                                                                                                                                                                                                  'multiplied. '
                                                                                                                                                                                                                  'With '
                                                                                                                                                                                                                  'the '
                                                                                                                                                                                                                  'train/test '
                                                                                                                                                                                                                  'split '
                                                                                                                                                                                                                  'the '
                                                                                                                                                                                                                  'test '
                                                                                                                                                                                                                  'phase '
                                                                                                                                                                                                                  'applies; '
                                                                                                                                                                                                                  'with '
                                                                                                                                                                                                                  'walk-forward '
                                                                                                                                                                                                                  'the '
                                                                                                                                                                                                                  'parameters '
                                                                                                                                                                                                                  'chosen '
                                                                                                                                                                                                                  'per '
                                                                                                                                                                                                                  'fold '
                                                                                                                                                                                                                  'apply.',
 'Robustheits-Test: Die Trades werden 1.000-mal zufällig neu gemischt bzw. gezogen. Statt einer einzelnen Zahl siehst du, wie stark Rendite und Drawdown streuen, und ob die Strategie besser ist als zufällige Einstiege mit gleicher Haltedauer (5 Zufalls-Seeds, die Spanne zeigt, ob das Ergebnis vom Zufall des Generators abhängt). Dazu 95-%-Konfidenzintervalle für Sharpe, Ø Trade und Trefferquote: Liegt die Untergrenze nicht über 0, ist der Vorteil statistisch nicht gesichert.': 'Robustness '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'test: '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'the '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'trades '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'are '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'randomly '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'reshuffled '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'or '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'redrawn '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 '1,000 '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'times. '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'Instead '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'of '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'a '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'single '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'number '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'you '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'see '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'how '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'widely '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'return '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'and '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'drawdown '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'spread, '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'and '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'whether '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'the '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'strategy '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'is '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'better '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'than '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'random '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'entries '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'with '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'the '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'same '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'holding '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'period '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 '(5 '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'random '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'seeds; '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'the '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'range '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'shows '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'whether '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'the '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'result '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'depends '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'on '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'the '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 "generator's "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'chance). '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'In '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'addition, '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 '95 '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 '% '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'confidence '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'intervals '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'for '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'Sharpe, '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'avg. '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'trade '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'and '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'hit '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'rate: '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'if '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'the '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'lower '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'bound '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'is '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'not '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'above '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 '0, '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'the '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'advantage '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'is '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'not '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'statistically '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'established.',
 'Nur {} Trades (unter 30): statistisch nicht belastbar, die Verteilung ist nur ein Anhaltspunkt.': 'Only {} trades (under 30): '
                                                                                                    'statistically not reliable, the '
                                                                                                    'distribution is only a rough guide.',
 '(p = {}, Spanne {} bis {} über 5 Seeds)': '(p = {}, range {} to {} over 5 seeds)',
 'Wahrscheinlichkeit auf Gewinn': 'Probability of profit',
 'nicht von 0 unterscheidbar': 'indistinguishable from 0',
 'über 0 gesichert': 'established above 0',
 'Zu wenige Trades ({}, mindestens {} nötig) für einen Robustheits-Test.': 'Too few trades ({}, at least {} needed) for a robustness test.',
 '~{#} Trades': '{} trades',
 '~{#} Trade': '{} trade',
 'Stark schwankende Parameter über die Folds deuten auf eine instabile Strategie hin.': 'Strongly fluctuating parameters across the folds '
                                                                                        'indicate an unstable strategy.',
 'Die Performance bricht auf ungesehenen Daten deutlich ein.': 'Performance drops significantly on unseen data.',
 'Nicht verfügbar: {}': 'Not available: {}'}
